spring:
    application:
        name: rootapp
    data:
        mongodb:
            uri: mongodb://root:root@db-container:27017/ggundb
    sql:
        init:
            mode: always
            encoding: UTF-8
logging:
    level:
        org:
            hibernate:
                SQL: debug
                type: trace